title: "π™π™ƒπ™π™€π™€ π™πΌπ™ π™π™π™π™‰π™„π™π™π™π™€"
logo: "docs/assets/IMG-20250928-WA0028.jpg"
description: "π™π™π™‹ π™π™πΌπ™‡π™„π™π™” π™π™π™π™‰π™„π™π™π™π™€"
# show_downloads: true
theme: "jekyll-theme-minimal"
