---
title: "ãŠâ”Šğ™á´‡É´Éªá´›êœ±á´œ"
logo: "docs/assets/IMG_20241221_094802_220.jpg"
description: "á´€ sÉªá´á´˜ÊŸá´‡ Ê™á´Ê"
theme: "jekyll-theme-minimal"
---

## á´€Ê™á´ÊŠá´› ãŠâ”Šğ™á´‡É´Éªá´›êœ±á´œ
Êœá´‡ÊÊ, Éª'á´ á´Šá´œsá´› á´€ Ê™á´Ê Ò“Ê€á´á´ á´œá´›á´›á´€Ê€ á´˜Ê€á´€á´…á´‡sÊœ á´¡Êœá´ Éªs á´›Ê€ÊÉªÉ´É¢ á´›á´ ÊŸá´‡á´€Ê€É´ sá´á´á´‡á´›ÊœÉªÉ´É¢ É´á´‡á´¡. Ò“á´Ê€ Ò“á´œá´›á´œÊ€á´‡ á´€É´á´… á´á´€á´‹á´‡ á´Ê sá´‹ÉªÊŸÊŸs É¢Ê€á´á´¡ & á´œá´˜É¢Ê€á´€á´…á´‡ 

<div align="left">
  <img src="https://readme-typing-svg.herokuapp.com?color=000000&center=true&lines=â”€â”€+ã€Œğ™ğ˜¼ğ™ƒğ™„ğ™‡ã€+â”€â”€&width=120&height=60">
</div>
 
 â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

â•°â”€â£[![telegram](https://img.shields.io/badge/Zenitsu-Telegram-blue?style=for-the-badge&logo=telegram)](https://t.me/zenitsu_x_thunder_breathing)

â•°â”€â£- [![Instagram](https://img.shields.io/badge/Zenix-Instagram-red?style=for-the-badge&logo=Instagram)](https://www.instagram.com/zenix._.0?igsh=MTBjMTBobXhxanQwYg==) 

â•°â”€â£- [![whatsApp](https://img.shields.io/badge/Zenitsu-Whatsapp-green?style=for-the-badge&logo=whatsApp)](https://wa.me/6283863879340) 

â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€- 

<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif">

<!-- Direct GIF Embed -->
![My GIF](https://raw.githubusercontent.com/TonyxTony/web/main/VID_20250202_181333_083.gif)
